exclude: ^docs/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs

      # validate PR name is following the naming convention
      # args: ['--pattern', '^(?!((((feature|release|bugfix)\/((([A-Z]{1,10})-?)[A-Z]+-\d+)[a-zA-Z0-9\-]+)$).*))']

  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 1.3.2
  #   hooks:
  #     - id: sqlfluff-lint
  #       additional_dependencies: ['sqlfluff-templater-dbt==1.3.1','dbt-snowflake==1.2.0']
