Project ERD {
    database_type: 'Snowflake'
    note: 'MC Bank Dimension Model'
}

// Analyze Layer

Table PREPAID.CUSTOMER_DIM [headercolor: #6699ff]{
  CUSTOMER_ID VARCHAR(255) [primary key, note: 'unique within a program']
  CUSTOMER_STATUS VARCHAR(255)
  CUSTOMER_TYPE VARCHAR(15) [note: 'Business or Personal']
  FIRST_NAME VARCHAR(255)
  LAST_NAME VARCHAR(255)
  DATE_OF_BIRTH DATE
  ADDRESS_1 VARCHAR(255)
  ADDRESS_2 VARCHAR(255)
  CITY VARCHAR(255)
  STATE VARCHAR(255)
  COUNTRY VARCHAR(255)
  ZIP VARCHAR(255)
  PRIMARY_PHONE_NUMBER VARCHAR(255)
  SECONDARY_PHONE_NUMBER VARCHAR(255)
  EMAIL VARCHAR(255)
  ID_TYPE_1 CHAR(2)
  ID_NUMBER_1 VARCHAR(255)
  ID_STATE_1 VARCHAR(255)
  ID_COUNTRY_1 VARCHAR(255)
  ID_ISSUED_DATE_1 DATE
  ID_EXPIRY_DATE_1 DATE
  ID_TYPE_2 CHAR(2)
  ID_NUMBER_2 VARCHAR(255)
  COUNTRY_CITIZENSHIP VARCHAR(255)
  TIN_TYPE CHAR(3)
  SSN VARCHAR(255)
  EIN VARCHAR(255)
  COMPANY_NAME VARCHAR(255)
  BUSINESS_ADDRESS_1 VARCHAR(255)
  BUSINESS_ADDRESS_2 VARCHAR(255)
  BUSINESS_ADDRESS_3 VARCHAR(255)
  BUSINESS_CITY VARCHAR(255)
  BUSINESS_STATE VARCHAR(255)
  BUSINESS_COUNTRY VARCHAR(255)
  BUSINESS_ZIP VARCHAR(255)
  LOCATION_ID VARCHAR(255)
  AGENT_USER_ID VARCHAR(255)
  USER_DATA_1 VARCHAR(255)
  USER_DATA_2 VARCHAR(255)  
  ID_VERIFICATION_RESULTS VARCHAR(15)
  ID_VERIFICATION_RESULTS_OVERRIDE VARCHAR(15)
  OTHER_INFO VARCHAR(255)
  CREATED_DATE DATE
  LAST_UPDATED_DATE DATE
  PROCESSOR_NAME VARCHAR(50) [primary key]
  BUSINESS_DATE DATE
  LOAD_DATE DATE
}

Table PREPAID.CARD_DIM [headercolor: #6699ff]{
  CARD_ID NUMBER [primary key]
  CARD_TYPE VARCHAR(255) 
  CARD_VALIDITY_DATE DATE
  CARD_EXPIRATION_DATE DATE
  CARD_STATUS VARCHAR(255)
  RELOADABLE_INDICATOR VARCHAR(255)
  PROGRAM_ID NUMBER 
  PROGRAM_DESCRIPTION VARCHAR(255)
  PRODUCT_ID NUMBER
  PRODUCT_DESCRIPTION VARCHAR(255)
  GROUP_ID NUMBER
  OTHER_INFO VARCHAR(255)
  CREATED_DATE DATE
  LAST_UPDATED_DATE DATE
  PROCESSOR_NAME VARCHAR(50) [primary key]
  BUSINESS_DATE DATE
  LOAD_DATE DATE
}

Table PREPAID.ACCOUNT_DIM [headercolor: #6699ff]{
  ACCOUNT_SK VARCHAR(255) [note: 'unique within a processor']
  ACCOUNT_ID VARCHAR(255) [primary key]
  EXTERNAL_ACCOUNT_ID VARCHAR(255)
  CUSTOMER_ID VARCHAR(255) [ref: - PREPAID.CUSTOMER_DIM.CUSTOMER_ID]
  ACCOUNT_CREATED_DATE DATE
  ACCOUNT_EXPIRATION_DATE DATE
  ACCOUNT_STATUS VARCHAR(255)
  CARD_ID NUMBER [ref: - PREPAID.CARD_DIM.CARD_ID]
  PROGRAM_ID  NUMBER [ref: - COMMON_DIM.PROGRAM_DIM.PROGRAM_ID]
  PROGRAM_DESCRIPTION VARCHAR(255)
  PRODUCT_ID NUMBER [ref: - COMMON_DIM.PRODUCT_DIM.PRODUCT_ID]
  PRODUCT_DESCRIPTION VARCHAR(255)
  PRN NUMBER
  BILL_CYCLE_DAY NUMBER  
  LAST_TRANSACTION_DATE DATE
  PSEUDO_DDA NUMBER
  OTHER_INFO VARCHAR(255)
  CREATED_DATE DATE
  LAST_UPDATED_DATE DATE
  PROCESSOR_NAME VARCHAR(50) [primary key]
  BUSINESS_DATE DATE
  LOAD_DATE DATE
}

Table PREPAID.BALANCE_SNAPSHOT_FACT [headercolor: #6699ff]{
  ACCOUNT_SK VARCHAR(255)
  ACCOUNT_ID VARCHAR(255) [primary key, ref: - PREPAID.ACCOUNT_DIM.ACCOUNT_ID]
  CUSTOMER_ID VARCHAR(255) [primary key]
  CURRENT_BALANCE NUMBER
  CURRENT_BALANCE_DATE DATE [ref: - COMMON_DIM.DATE_DIM.DATE_VAL]
  AVAILABLE_BALANCE NUMBER
  NEGATIVE_BALANCE_DATE DATE
  NEGATIVE_BALANCE_FEE NUMBER
  CURRENCY_CODE VARCHAR(15)
  FX_RATE NUMBER
  PROCESSOR_NAME VARCHAR(50) [primary key]
  BUSINESS_DATE DATE
  LOAD_DATE DATE
}

Table PREPAID.TRANSACTION_FACT [headercolor: #6699ff]{
  ACCOUNT_SK VARCHAR(255)
  ACCOUNT_ID VARCHAR(255)  [primary key, ref: - PREPAID.ACCOUNT_DIM.ACCOUNT_ID]
  CUSTOMER_ID VARCHAR(255)
  TRANSACTION_ID VARCHAR(255) [primary key]
  TRANSACTION_CODE VARCHAR(255)
  TRANSACTION_AMOUNT NUMBER
  TRANSACTION_CURRENCY_CODE VARCHAR(15)
  LOCAL_TRANSACTION_AMOUNT NUMBER
  LOCAL_TRANSACTION_CURRENCY_CODE  VARCHAR(15)
  ORIGINAL_TRANSACTION_AMOUNT NUMBER
  TRANSACTION_DESCRIPTION VARCHAR(255)
  TRANSACTION_TYPE VARCHAR(255)
  TRANSACTION_STATUS VARCHAR(255)
  TRANSACTION_DATE DATE [ref: - COMMON_DIM.DATE_DIM.DATE_VAL]
  TRANSACTION_NOTE VARCHAR(1024)
  RESPONSE_CODE VARCHAR(255)
  AUTHORIZATION_CODE VARCHAR(255)
  POST_DATE DATE
  NETWORK_CODE CHAR(1)
  MERCHANT_NUMBER VARCHAR(255)
  MERCHANT_NAME VARCHAR(255)
  MERCHANT_CITY VARCHAR(255)
  MERCHANT_STATE VARCHAR(255)
  MERCHANT_ZIP VARCHAR(255)
  MERCHANT_CATEGORY VARCHAR(255)
  MERCHANT_COUNTRY VARCHAR(255)
  INTERCHANGE_FEE VARCHAR(255)
  FOREIGN_TERMINAL VARCHAR(255)
  POS_INDICATOR VARCHAR(255)
  SETTLEMENT_DATE DATE
  PSEUDO_DDA NUMBER
  OTHER_DATA_1 VARCHAR(255)
  OTHER_DATA_2 VARCHAR(255)
  DEBIT_PARTY_TYPE VARCHAR(255)
  DEBIT_PARTY_ACCOUNT_ID VARCHAR(255)
  DEBIT_PARTY_NAME VARCHAR(255)
  DEBIT_PARTY_ADDRESS_1 VARCHAR(255)
  DEBIT_PARTY_ADDRESS_2 VARCHAR(255)
  DEBIT_PARTY_ADDRESS_3 VARCHAR(255)
  DEBIT_VALUE_DATE DATE
  DEBIT_PARTY_COUNTRY VARCHAR(255)
  CREDIT_PARTY_TYPE VARCHAR(255)
  CREDIT_PARTY_ACCOUNT_ID VARCHAR(255)
  CREDIT_PARTY_NAME VARCHAR(255)
  CREDIT_PARTY_ADDRESS_1 VARCHAR(255)
  CREDIT_PARTY_ADDRESS_2 VARCHAR(255)
  CREDIT_PARTY_ADDRESS_3 VARCHAR(255)
  CREDIT_VALUE_DATE DATE
  CREDIT_PARTY_COUNTRY VARCHAR(255)
  INTERMEDIARY_PARTY_TYPE VARCHAR(255)
  INTERMEDIARY_PARTY_ID VARCHAR(255)
  INTERMEDIARY_PARTY_NAME VARCHAR(255)
  INTERMEDIARY_PARTY_ADDRESS_1 VARCHAR(255)
  INTERMEDIARY_PARTY_ADDRESS_2 VARCHAR(255)
  INTERMEDIARY_PARTY_ADDRESS_3 VARCHAR(255)
  INSTRUCTING_PARTY_TYPE VARCHAR(255)
  INSTRUCTING_PARTY_ID VARCHAR(255)
  INSTRUCTING_PARTY_NAME VARCHAR(255)
  INSTRUCTING_PARTY_ADDRESS_1 VARCHAR(255)
  INSTRUCTING_PARTY_ADDRESS_2 VARCHAR(255)
  INSTRUCTING_PARTY_ADDRESS_3 VARCHAR(255)
  BENEFICIARY_BANK_ROUTING_PARTY_TYPE VARCHAR(255)
  BENEFICIARY_BANK_ROUTING_PARTY_ID VARCHAR(255)
  BENEFICIARY_BANK_ROUTING_PARTY_NAME VARCHAR(255)
  BENEFICIARY_BANK_ROUTING_PARTY_ADDRESS_1 VARCHAR(255)
  BENEFICIARY_BANK_ROUTING_PARTY_ADDRESS_2 VARCHAR(255)
  BENEFICIARY_BANK_ROUTING_PARTY_ADDRESS_3 VARCHAR(255)
  BENEFICIARY_BANK_PARTY_TYPE VARCHAR(255)
  BENEFICIARY_BANK_PARTY_ID VARCHAR(255)
  BENEFICIARY_BANK_PARTY_NAME VARCHAR(255)
  BENEFICIARY_BANK_PARTY_ADDRESS_1 VARCHAR(255)
  BENEFICIARY_BANK_PARTY_ADDRESS_2 VARCHAR(255)
  BENEFICIARY_BANK__PARTY_ADDRESS_3 VARCHAR(255)
  PROCESSOR_NAME VARCHAR(50) [primary key]
  BUSINESS_DATE DATE
  LOAD_DATE  DATE
}


Table PREPAID.RECON [headercolor: #6699ff]{
  CUSTOMER_ID VARCHAR(255) [primary key]
  ACCOUNT_ID VARCHAR(255) [primary key]
  TRANSACTION_ID VARCHAR(15) [primary key]
  RECON_STATUS VARCHAR(255)
  RECON_RESULTS VARCHAR(512)  
  PROCESSOR_NAME VARCHAR(50) [primary key]
  BUSINESS_DATE DATE
  LOAD_DATE DATE
}

Table COMMON_DIM.DATE_DIM [headercolor: #6699ff]{ 
  DATE_ID NUMBER [primary key]
  DATE_VAL DATE
  YEAR NUMBER
  DOW NUMBER
  MOY NUMBER
  DOM NUMBER
  QOY NUMBER
  DAY_NAME VARCHAR(15)
  MONTH_NAME VARCHAR(15)
  QUARTER_NAME VARCHAR(15)
  WEEKEND CHAR(1)
  FIRST_DOM NUMBER
  LAST_DOM NUMBER
  MONTH_END CHAR(1)
  QUARTER_END CHAR(1)
  YEAR_END CHAR(1)
}

Table COMMON_DIM.LOOKUP [headercolor: #6699ff]{
  ENTITY_NAME VARCHAR(255) [primary key]
  FIELD_NAME VARCHAR(255) [primary key]
  CODE VARCHAR(15) [primary key]
  DESCRIPTION VARCHAR(255)  
  OTHER_INFO VARCHAR(255)
  PROCESSOR_NAME VARCHAR(50) [primary key]
  BUSINESS_DATE DATE
  LOAD_DATE DATE
}


Table COMMON_DIM.PROGRAM_DIM [headercolor: #6699ff]{
  PROGRAM_ID NUMBER [primary key]
  PROGRAM_DESCRIPTION VARCHAR(255)
  PROCESSOR_NAME VARCHAR(50)
  CREATED_DATE DATE
  CREATED_BY VARCHAR(50)
  LAST_UPDATED_DATE DATE
  LAST_UPDATED_BY VARCHAR(50)
}

Table COMMON_DIM.PRODUCT_DIM [headercolor: #6699ff]{
  PRODUCT_ID NUMBER [primary key]
  PRODUCT_DESCRIPTION VARCHAR(255)
  PROCESSOR_NAME VARCHAR(50)
  CREATED_DATE DATE
  CREATED_BY VARCHAR(50)
  LAST_UPDATED_DATE DATE
  LAST_UPDATED_BY VARCHAR(50)
}