{{ config(
    tags=["integrate","prepaid"],
    alias='transaction_fact',
    schema='prepaid'
    )
}}

select 
    a.SURROGATE_PROXY_TOKEN_UNIQUE_ID as ACCOUNT_SK
    , a.ACCOUNT_NUMBER as ACCOUNT_ID
    , b.CUSTOMER_ID
    , a.TRANSACTION_ID
    , a.TRANSACTION_CODE
    , a.TRANSACTION_AMOUNT
    , a.TRANSACTION_CURRENCY as TRANSACTION_CURRENCY_CODE
    , a.TRANSACTION_AMOUNT_LOCAL as LOCAL_TRANSACTION_AMOUNT
    , a.TRANSACTION_CURRENCY_LOCAL_CODE as LOCAL_TRANSACTION_CURRENCY_CODE
    , a.ORIGINAL_TRANSACTION_AMOUNT
    , a.TRANSACTION_DESCRIPTION
    , a.TRANSACTION_TYPE
    , a.TRANSACTION_STATUS
    , a.TRANSACTION_DATE
    , a.TRANSACTION_NOTE
    , a.RESPONSE_CODE
    , a.AUTHORIZATION_CODE
    , a.POST_DATE
    , a.NETWORK_CODE
    , a.MERCHANT_NUMBER
    , a.MERCHANT_NAME
    , a.MERCHANT_CITY
    , a.MERCHANT_STATE
    , a.MERCHANT_ZIP
    , a.MERCHANT_CATEGORY
    , a.MERCHANT_COUNTRY
    , a.INTERCHANGE_FEE
    , a.FOREIGN_TERMINAL
    , a.POS_INDICATOR
    , a.SETTLED_DATE as SETTLEMENT_DATE
    , a.PSEUDO_DDA as PSEUDO_DDA
    , a.OTHER_DATA1 as OTHER_DATA_1
    , a.OTHER_DATA2 as OTHER_DATA_2
    , a.DEBIT_PARTY_TYPE
    , a.DEBIT_PARTY_ACCOUNT_NUMBER as DEBIT_PARTY_ACCOUNT_ID
    , a.DEBIT_PARTY_NAME
    , a.DEBIT_PARTY_ADDR_1 as DEBIT_PARTY_ADDRESS_1
    , a.DEBIT_PARTY_ADDR_2 as DEBIT_PARTY_ADDRESS_2
    , a.DEBIT_PARTY_ADDR_3 as DEBIT_PARTY_ADDRESS_3
    , a.DEBIT_VALUE_DATE
    , a.DEBIT_PARTY_COUNTRY
    , a.CREDIT_PARTY_TYPE
    , a.CREDIT_PARTY_ACCOUNT_NUMBER as CREDIT_PARTY_ACCOUNT_ID
    , a.CREDIT_PARTY_NAME
    , a.CREDIT_PARTY_ADDR_1 as CREDIT_PARTY_ADDRESS_1
    , a.CREDIT_PARTY_ADDR_2 as CREDIT_PARTY_ADDRESS_2
    , a.CREDIT_PARTY_ADDR_3 as CREDIT_PARTY_ADDRESS_3
    , a.CREDIT_VALUE_DATE
    , a.CREDIT_PARTY_COUNTRY
    , a.INTERMEDIARY_3RD_PARTY_TYPE as INTERMEDIARY_PARTY_TYPE
    , a.INTERMEDIARY_ACCOUNT_3RD_PARTY_ID as INTERMEDIARY_PARTY_ID
    , a.INTERMEDIARY_3RD_PARTY_NAME as INTERMEDIARY_PARTY_NAME
    , a.INTERMEDIARY_3RD_PARTY_ADDR_1 as INTERMEDIARY_PARTY_ADDRESS_1
    , a.INTERMEDIARY_3RD_PARTY_ADDR_2 as INTERMEDIARY_PARTY_ADDRESS_2
    , a.INTERMEDIARY_3RD_PARTY_ADDR_3 as INTERMEDIARY_PARTY_ADDRESS_3
    , '' as INSTRUCTING_PARTY_TYPE
    , '' as INSTRUCTING_PARTY_ID
    , a.INSTRUCTING_PARTY_NAME
    , a.INSTRUCTING_PARTY_ADDR_1 as INSTRUCTING_PARTY_ADDRESS_1
    , a.INSTRUCTING_PARTY_ADDR_2 as INSTRUCTING_PARTY_ADDRESS_2
    , a.INSTRUCTING_PARTY_ADDR_3 as INSTRUCTING_PARTY_ADDRESS_3
    , a.BENEFICIARY_4TH_PARTY_TYPE as BENEFICIARY_BANK_ROUTING_PARTY_TYPE
    , a.BENEFICIARY_BANK_ID_4TH_PARTY_ID as BENEFICIARY_BANK_ROUTING_PARTY_ID
    , a.BENEFICIARY_BANK_ROUTING_4TH_PARTY_NAME as BENEFICIARY_BANK_ROUTING_PARTY_NAME
    , a.BENEFICIARY_BANK_4TH_PARTY_ADDR_1 as BENEFICIARY_BANK_ROUTING_PARTY_ADDRESS_1
    , a.BENEFICIARY_BANK_4TH_PARTY_ADDR_2 as BENEFICIARY_BANK_ROUTING_PARTY_ADDRESS_2
    , a.BENEFICIARY_BANK_4TH_PARTY_ADDR_3 as BENEFICIARY_BANK_ROUTING_PARTY_ADDRESS_3
    , a.BENEFICIARY_5TH_PARTY_TYPE as BENEFICIARY_BANK_PARTY_TYPE
    , a.BENEFICIARY_ID_5TH_PARTY_ID as BENEFICIARY_BANK_PARTY_ID
    , a.BENEFICIARY_NAME_5TH_PARTY_NAME as BENEFICIARY_BANK_PARTY_NAME
    , a.BENEFICIARY_5TH_PARTY_ADDR_1 as BENEFICIARY_BANK_PARTY_ADDRESS_1
    , a.BENEFICIARY_5TH_PARTY_ADDR_2 as BENEFICIARY_BANK_PARTY_ADDRESS_2
    , a.BENEFICIARY_5TH_PARTY_ADDR_3 as BENEFICIARY_BANK__PARTY_ADDRESS_3
    , a.PAYMENT_PROCESSOR as PROCESSOR_NAME
    from {{ ref('prepaid__normalize_transaction') }} a
        left join {{ ref('prepaid__integrate_account') }} b
            on trim(a.ACCOUNT_NUMBER) = trim(b.ACCOUNT_ID)  and trim(a.PAYMENT_PROCESSOR) = trim(b.PROCESSOR_NAME)
